# Base configs
baseurl: "https://alexdanila.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Alex Danila"
subtitle: "See the world through my eyes!"
author: "Alex Danila"
header:
 title: "Photography"
 subtitle: "by Alex Danila"
footer:
 name: "Alex Danila"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/alexanderdanila"
  instagram: "https://www.instagram.com/alexanderdanila"
  linkedin: "https://in.linkedin.com/in/alexdanila"

